Fixed localization
go-gitea/website pull request #14
Opened 2016-12-09 14:08 UTC by tboerger

2016-12-09 14:10 UTC, tboerger commented
Requires the theme changes at https://github.com/go-gitea/theme/pull/16

2016-12-09 14:20 UTC, lunny commented
build failed?

2016-12-09 14:38 UTC, tboerger commented
See the comment above

2016-12-09 15:29 UTC, tboerger commented
Build fixed

2016-12-09 15:44 UTC, Bwko commented
LGTM

2016-12-09 15:58 UTC, bkcsoft requested changes
If I press "Chinese" I expect to get things in Chinese 🙂

2016-12-09 15:58 UTC, bkcsoft commented on content/index.zh-cn.md
> +# Gitea - Git with a cup of tea
Maybe @lunny can translate this before merging?

2016-12-09 15:59 UTC, bkcsoft commented on content/index.zh-cn.md
> +# Gitea - Git with a cup of tea
Otherwise I can translate to Swedish tomorrow 😛

2016-12-09 16:07 UTC, tboerger commented on content/index.zh-cn.md
> +# Gitea - Git with a cup of tea
Let lunny do that in a followup pr, currently we got something to see that the i18n stuff works

2016-12-09 18:54 UTC, metalmatze commented
LGTM

2016-12-09 19:06 UTC, bkcsoft approved these changes

2016-12-09 19:06 UTC, merged

2016-12-10 01:34 UTC, lunny commented on content/index.zh-cn.md
> +# Gitea - Git with a cup of tea
https://github.com/go-gitea/website/pull/15
and how to enter the right language according browser setting?