Add instances
go-gitea/website pull request #71
Opened 2018-06-06 15:51 UTC by genofire

implement #70 
I did not know a nice multilingual solution without make changes of hugo gitea themen.
(is there any reason why it is not inside this repository)

2018-06-06 15:53 UTC, techknowlogick requested changes

2018-06-06 15:53 UTC, techknowlogick commented on config.yaml
> +      weight: 50
There is no need to modify the weight of the other items in the list. You can set instances weight to 35 and achieve the same outcome.

2018-06-06 15:57 UTC, techknowlogick commented on content/instances/instances.md
> +| [git.spacegit.xyz](https://git.spacegit.xyz)      |  ✔ / ✔  |   ✔ / ✔   |                ✔ / ✘   |                    ✘ / ✘   | [see](https://git.spacegit.xyz/)   |
git.spacegit.xyz offers free private hosting as well, and orgs. (orgs by request). However if users want us to host a different install for them then we charge.

2018-06-06 15:59 UTC, lunny commented
And the service is permanent or temporary?

2018-06-06 18:26 UTC, genofire commented on content/instances/instances.md
> +| [git.spacegit.xyz](https://git.spacegit.xyz)      |  ✔ / ✔  |   ✔ / ✔   |                ✔ / ✘   |                    ✘ / ✘   | [see](https://git.spacegit.xyz/)   |
sry, i miss understand

2018-06-06 18:27 UTC, genofire commented
@lunny do you want a guarante column with x years or months?

2018-06-06 23:12 UTC, lunny commented
@genofire yes

2018-06-14 15:49 UTC, techknowlogick commented
@genofire with teahub coming soon I'm actually going to shutdown git.spacegit.xyz so you can remove it from the list.

2019-01-10 22:38 UTC, genofire commented
We run gitlab ATM, sry ...

Be free to hijack this PR

2019-01-10 22:38 UTC, closed without merging